export const PEMEX_KEYWORDS = [
  'Pemex',
  'Sener Mexico',
  'Juan Carlos Carpio Fragoso',
  'Director General Pemex',
  'Hidrocarburos Mexico',
  'Huachicol',
  'Toma Clandestina combustible',
  'Pemex Gas',
  'Pemex Diesel',
  'Pemex Gasolina',
  'Pemex Petroleo',
  'Refineria Cadereyta',
  'Pemex Contaminacion',
  'Pemex Desabasto',
  'Robo combustible Mexico',
  'Pemex Ducto',
  'Pemex Poliducto',
  'Pemex Gasoducto',
  'Pemex Pipa',
  'Pemex Autotanque',
  'Pemex Terminal almacenamiento',
  'Pemex TAD',
  'Pemex Gas LP',
  'Pemex Incendio',
  'Pemex Explosion',
  'Pemex Derrame',
  'Pemex Fuga',
];
