export const PEMEX_KEYWORDS = [
  'Pemex',
  'Director General Pemex Juan Carlos Carpio',
  'Juan Carlos Carpio Fragoso',
  'Refineria Cadereyta',
  'Gasolina Mexico',
  'Pipa combustible Mexico',
  'Petroleo Mexico',
  'Diesel Mexico',
  'Toma clandestina combustible',
  'Huachicol',
  'Pemex explosion',
  'Pemex incendio',
  'Pemex fuga',
  'Ducto Pemex',
  'Pemex derrame',
  'Deuda Pemex',
  'Soberania energetica Mexico',
  'Produccion petrolera Mexico',
  'Rescate financiero Pemex',
  'Corrupcion Pemex',
  'Contaminacion Pemex',
  'Calidad del aire Monterrey',
  'Produccion crudo Mexico',
  'Refinacion Pemex',
  'Gas natural Mexico',
  'Petroquimica Pemex',
  'Fertilizantes Pemex',
  'Pemex Sener',
  'Pemex desabasto',
  'Pemex robo combustible',
];
